### ISSUE TITLE
Asking for Masquerade permission even when enabled.

### ISSUE THREAD

**Issue by MythicalTrashcan** [mayudev/revcord#19]
I have connected the bots together and experimented and it seems messages from Revolt to Discord work perfectly, but Discord to Revolt doesn't send. It is asking for the bot to have the Masquerade permission, but I made a role giving it every permission including Masquerade. Was I supposed to do something differently to give this permission because the only way I knew to give the Masquerade permission was through a role.

**Comment by mayudev** [comment]
Generally, the permission error appears after Revolt has already rejected the message, so it most likely an issue with permissions of the bot on your server. And yes, you're supposed to make a role with Masquerade permission enabled and assign it to the bot.

**Comment by MythicalTrashcan** [comment]
![Role1](https://github.com/mayudev/revcord/assets/79861302/04e49b4e-5f85-4112-9f78-ff66faed0b8f)
![Role2](https://github.com/mayudev/revcord/assets/79861302/890ceb75-12cf-45ac-bd86-ebd84fd38b1a)

[Revcord Error Log.txt](https://github.com/mayudev/revcord/files/11996073/Revcord.Error.Log.txt)

I am not sure what the errors mean. I went and redid the revcord setup and still got the same error.

**Comment by mayudev** [comment]
Honestly I don't know what the issue may be caused by, but I'm pretty sure it's something on Revolt side. Maybe make sure the bot role has permissions to send messages in the specific channel.

Also the bot token seemed to be included with the logs, so I deleted them, but I suggest you regenerate the token as well. The logs leaking tokens is an issue on revolt.js side (we're just displaying the error message from there) but I guess it's hidden among a wall of text so I'll try to find a solution on our side so that it never happens again.

**Comment by MythicalTrashcan** [comment]
I see. It seems that the permissions for the bot role are overridden by channel permissions. I didn't set anything for the bots role in the channel and it just treated the bots role as if there was no permissions for whatever reason. It seems setting the permissions for the bots role and in the channel you connect is necessary. Problem solved.
