### ISSUE TITLE
Discord messages show up as blank

### ISSUE THREAD

**Issue by unclamped** [mayudev/revcord#7]
No error logs, Discord users can see Revolt user's messages, but not vice versa
![image](https://user-images.githubusercontent.com/104658278/219540232-1fd4f817-38d2-4a5c-9741-7efc16c75a43.png)
![image](https://user-images.githubusercontent.com/104658278/219540262-7726eb66-aac5-438d-84e1-9050d43630d2.png)

**Comment by mayudev** [comment]
You most likely didn't enable the message content intent in discord developer settings, so the bot can't access the content of messages on Discord

**Comment by unclamped** [comment]
> You most likely didn't enable the message content intent in discord developer settings, so the bot can't access the content of messages on Discord

It doesn't seem to be that. I also included the Read Messages/View Channels intent just in case, yet nothing. The bot also has full admin perms just for testing

**Comment by mayudev** [comment]
It's not the same as permission, it's a separate thing in the Bot > Privileged Gateway Intents section. You need to enable the Message Content Intent.

Admittedly, I forgot to add a notice about that in readme because it was a fairly recent change, I'll make sure to do that later.

![image](https://user-images.githubusercontent.com/99561108/219946599-e18ad939-8cee-49a0-bbb8-915fd2e31ff8.png)

**Comment by unclamped** [comment]
I forgot to reply, whoops. Yeah, that solved the issue. Thanks!
